src/AppBundle/Entity/Rdv.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * Rdv
 * @Vich\Uploadable
 */
class Rdv
{
    use TimestampableTrait;
    #region *******************Attributes region***************************

    /**
     * @var int
     */
    private $id;
	
	 /**
     * @var int
     */
    private $placeId;
	
	/**
     * @var decimal
     */
    private $note;
	
	/**
     * @var decimal
     */
    private $price;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $niveau;

    /**
     * @var File
     * @Vich\UploadableField(mapping="ad_image", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @var string
     */
    private $imageName;

    /**
     * @var boolean
     */
    private $published;

    #endregion

    #region *******************Mappings region***************************

    /**
     * @var ArrayCollection
     */
    private $tags;

    /**
     * @var Category
     */
    private $category;

    /**
     * @var SubCategory
     */
    private $subCategory;

    /**
     * @var ArrayCollection
     */
    private $sessions;

    /**
     * @var User
     */
    private $author;
	
	/**
     * @var Place
     */
    private $place;
	
	/**
     * @var Partitipation
     */
    private $participation;

    #endregion

    #region *******************Methods region***************************

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
	


    /**
     * Set title
     *
     * @param string $title
     *
     * @return Rdv
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
	
	 /**
     * Get price
     *
     * @return decimal
     */
    public function getPrice()
    {
        return $this->price;
    }
	
	/**
     * Get note
     *
     * @return decimal
     */
    public function getNote()
    {
        return $this->note;
    }
	
	 /**
	 * Get place
	 *
     * @return place
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * @param int $place
	 *
     * @return Rdv
     */
    public function setPlace($place)
    {
        $this->place = $place;
        return $this;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Rdv
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return string
     */
    public function getNiveau()
    {
        return $this->niveau;
    }

    /**
     * @param string $niveau
     */
    public function setNiveau($niveau)
    {
        $this->niveau = $niveau;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @param Tag $tag
     */
    public function addTag($tag)
    {
        $tag->setRdv($this);
        $this->tags->add($tag);
        return $this;
    }

    /**
     * @param Tag $tag
     */
    public function removeTag($tag)
    {
        $this->tags->removeElement($tag);
        return $this;
    }

    /**
     * @param ArrayCollection $tags
     */
    public function setTags($tags)
    {
        $this->tags = $tags;
        return $this;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
        return $this;
    }

    /**
     * @return SubCategory
     */
    public function getSubCategory()
    {
        return $this->subCategory;
    }

    /**
     * @param SubCategory $subCategory
     */
    public function setSubCategory($subCategory)
    {
        $this->subCategory = $subCategory;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getSessions()
    {
        return $this->sessions;
    }

    /**
     * @var ArrayCollection
     */
    public function getRemainingSessions()
    {
        $oTodayDate = new \DateTime('NOW');

        return $this->sessions->filter(function (Session $oSession) use ($oTodayDate){
            if ($oSession->getDateSession() > $oTodayDate)
                return $oSession;
        });
    }

    /**
     * @param ArrayCollection $sessions
     */
    public function setSessions($sessions)
    {
        $this->sessions = $sessions;
        return $this;
    }

    /**
     * @param Session $session
     */
    public function addSession($session)
    {
        $session->setRdv($this);
        $this->sessions->add($session);
        return $this;
    }

    /**
     * @param Session $session
     */
    public function removeSession($session)
    {
        $this->sessions->removeElement($session);
        return $this;
    }

    /**
     * @return Session
     */
    public function getClosestSession() {
        $oTodayDate = new \DateTime('NOW');

        $cValidSessions = $this->sessions->filter(function (Session $oSession) use ($oTodayDate){
            if ($oSession->getDateSession() > $oTodayDate)
                return $oSession;
        });

        $oIterator = $cValidSessions->getIterator();
        $oIterator->uasort(function (Session $oSession1, Session $oSession2){
            return ($oSession1->getDateSession() > $oSession2->getDateSession()) ?1 : -1;
        });

        return (new ArrayCollection(iterator_to_array($oIterator)))->first();
    }

    /**
     * @return User
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param User $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
        return $this;
    }
	
	

    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @return bool
     */
    public function isPublished(): bool
    {
        return $this->published;
    }

    /**
     * @param bool $published
     */
    public function setPublished(bool $published)
    {
        $this->published = $published;
        return $this;
    }



    /**
     * @Assert\Callback
     * @param ExecutionContextInterface $context
     */
    public function validate(ExecutionContextInterface $context)
    {

        //Wrong file MIME type
        if ($this->imageFile && !in_array($this->imageFile->getMimeType(), array(
                'video/bmp',
                'image/jpeg',
                'image/png'
            ))) {
            $context
                ->buildViolation("Format d'image non approprié")
                ->atPath('imageName')
                ->addViolation()
            ;

        }
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->published = false;
    }

    #endregion
}

src/AppBundle/Controller/ConsultantController.php
<?php
/**
 * Created by Safouane Fakhfakh.
 * Email: Safouane.Fakhfakh@mail.com
 */

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ConsultantController extends Controller
{
    public function profileAction($id)
    {
        $oEm = $this->getDoctrine()->getManager();
        $oConsultant = $oEm->getRepository('AppBundle:User')->find($id);

        return $this->render('AppBundle:consultant:profile.html.twig', array(
           'consultant' => $oConsultant,
        ));
    }
}

src/AppBundle/Resources/views/consultant/profile.html.twig
{% extends 'AppBundle::base.html.twig' %}
{% block title %}
    <title>Profil Consultant</title>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <style>
        .valid-put {
            -webkit-box-shadow: 0px 0px 7px 1px rgba(0, 255, 0, 1);
            -moz-box-shadow: 0px 0px 7px 1px rgba(0, 255, 0, 1);
            box-shadow: 0px 0px 7px 1px rgba(0, 255, 0, 1);
        }

        .invalid-put {
            -webkit-box-shadow: 0px 0px 7px 1px rgba(255, 0, 0, 1);
            -moz-box-shadow: 0px 0px 7px 1px rgba(255, 0, 0, 1);
            box-shadow: 0px 0px 7px 1px rgba(255, 0, 0, 1);
        }

        .oblig-put {
            color: red;
        }
        .arrow-up {
            margin-left: 177px;
            width: 0;
            height: 0;
            border-left: 5px solid transparent;
            border-right: 5px solid transparent;
            border-bottom: 5px solid #ffc107;
        }
        .arr-cartinf{
            display: none;
            margin-bottom: 4px;
        }
        .cartid-info {
            -webkit-box-shadow: 0px 0px 7px 1px rgba(255, 0, 0, 1);
            -moz-box-shadow: 0px 0px 7px 1px rgba(255, 0, 0, 1);
            box-shadow: 0px 0px 7px 1px rgba(255, 193, 7, 1);
        }
    </style>
{% endblock %}
{% block body %}
    <!-- /.container -->
    <div class="container">
        <i class="fas fa-arrow-alt-circle-left"></i>&nbsp<a class="text-dark" href="{{ path('index') }}">Retour</a>
    </div>

    <div class="bg-secondary text-white mt-2">
        <div class="media container">
            <img class="mr-3 my-2" src="{{ asset('uploads/images/profile/'~consultant.imageName) }}" width="120"
                 height="120" alt="Generic placeholder image">
            <div class="media-body mt-3">
                <h5 class="mt-0">{{ consultant.firstName }} {{ consultant.lastName }}</h5>
                <p>Dire quelque chose</p>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>

    <div class="container">
        <div class=" justify-content-center my-2 w-75">
            <h5>A Propos De Moi</h5>
            <p>{{ consultant.biography }}</p>
            <hr>
        </div>
        <div class=" justify-content-center my-2 w-75">
            <h5>Mon Parcours Professionnel</h5>
            <p>-Situation actuelle: {{ consultant.proSituation }}</p>
            <p>-Niveau académique: {{ consultant.education }}</p>
            <hr>
        </div>
        <div class=" justify-content-center my-2 w-75">
            <h5>Expérience Pro</h5>
            {% for experience in consultant.professionalExperiences %}
                <i>{{ experience.startYear|date('Y') ~ '-' ~ experience.endYear|date('Y') }}</i>
                <p>{{ experience.title ~ ' ,' ~ experience.entreprise }}</p>
            {% endfor %}
            <hr>
        </div>
        <div class=" justify-content-center my-2 w-75">
            <h5>Mon Cursus Académique</h5>
            {% for diploma in consultant.diplomas %}
                <i>{{ diploma.startYear|date('Y') ~ '-' ~ diploma.endYear|date('Y') }}</i>
                <p>{{ diploma.diploma ~ ' ,' ~ diploma.studyField }}</p>
            {% endfor %}
        </div>

        <div class=" justify-content-center my-2 w-75">
            <h5>Mes Centres D’intérêt</h5>
            <div class="my-2">
                {% for interest in consultant.interests %}
                    <span class="badge badge-warning">{{ interest.name }}</span>
                {% endfor %}
            </div>
            <hr>
        </div>
        <div class=" justify-content-center my-2 w-75">
            <h5>Mes derniers RDV organisés</h5>
            <div class="cont-autre-rdv">
                <div class="row">
                    {% for rdv in consultant.rdvs %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#"><img class="card-img-top"
                                                 src="{{ asset('uploads/images/ad/'~rdv.imageName) }}" alt=""></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a class="rdv-annoce-title" href="#">{{ rdv.title }}</a>
                                    </h4>
                                    <span><i class="fas fa-map-marker-alt"></i>&nbsp<span>{{ rdv.closestSession.place.city }}</span>&nbsp-&nbsp<span>{{ rdv.closestSession.place.city }}</span></span><br>
                                    <span><i class="far fa-clock"></i>&nbsp<span>{{ rdv.closestSession.dateSession|date('d/m/Y') }}</span>&nbspà&nbsp<span>{{ rdv.closestSession.startTime|date('H') ~ 'h' ~ rdv.closestSession.startTime|date('i') }}</span></span>

                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                    </small>
                                    <div class="float-lg-right font-weight-bold">
                                        <span>{{ rdv.closestSession.price }}</span>
                                        <span>TND</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <hr>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts '@AppBundle/Resources/public/src/scripts/consultant/profile.js' output='assets/scripts/consultant/profile.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}